services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: advocacia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/advocacia
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    environment:
      NUXT_PUBLIC_API_BASE: http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data: