name: CI/CD Pipeline

on:
  push:
    branches: [master, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: advocacia
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: [5432:5432]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build backend
        run: |
          cd backend
          ./mvnw package -DskipTests

      - name: Test backend
        run: |
          cd backend
          ./mvnw test

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Docker Compose Build
        run: docker-compose build

      # Adicione steps para push em registry e deploy conforme sua necessidade
